[project]
name = "mcs-ml-first"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "arpangreat", email = "arpanthegreat41@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-auth>=2.58.0",
    "google-genai>=2.23.0",
    "ipython>=9.17.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "neo4j>=6.3.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "rich>=15.0.0",
    "scikit-learn>=1.9.1",
]

[project.scripts]
mcs-ml-first = "mcs_ml_first:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "GraphRAG",
    "assignments/linear-regression",
    "assignments/multiple-linear-regression",
]
